### PR TITLE
Don't allow spaces in Nicknames

### PR DESCRIPTION
**Pull request by slowbro**
This fixes issues seen in matterircd/issues#120 with spaces in the nicknames presented to IRC clients.

### CODE REVIEW

**Comment by 42wim** [comment]
I've been thinking about this, and maybe it's better to just reverse this feature (added in https://github.com/42wim/mm-go-irckit/commit/e24f2ffd2c206145bf3b1d8abaae9b60f05ff200)  completely.

If nicknames contain utf-8 it's also going to give an issue, usernames on the other hand should be always safe.

**Comment by slowbro** [comment]
I think that's fine, too - mostly it just adds lots of 'what ifs'

Alternatively, it could be toggled by a flag, and unacceptable characters could be stripped (only allowing A-z0-9-_|{}[]^`)

**Comment by slowbro** [comment]
Did you know the final direction you wanted to go with on this?

**Comment by 42wim** [comment]
Oops, forgot about this, commit has been reverted.
I'm going to close this also

**Pull request closed without merging**
